filter_sets:
    article_full:
        quality: 85
        filters:
            centercrop: [846, 380]
    article_topic:
        quality: 85
        filters:
            downscale: { max: [846, 846] }
    article_grid_2:
        quality: 85
        filters:
            centercrop: [570, 280]
    article_grid_3:
        quality: 85
        filters:
            centercrop: [400, 280]
    article_grid_4:
        quality: 85
        filters:
            downscale: { max: [846, 380] }
    article_grid_6:
        quality: 85
        filters:
            centercrop: [300, 250]
    campaign_1:
        quality: 85
        filters:
            centercrop: [846, 378]
    right_thumb:
        quality: 85
        filters:
            downscale: { max: [300, 300] }
            centercrop: [300,300]