system:
    tfk_school_group:
        user:
            layout: tfktelemarkSkoleBundle::pagelayout.html.twig
            login_template: tfktelemarkSkoleBundle:security:login.html.twig
        content_view:
            full:
                landing_page:
                    template: tfktelemarkSkoleBundle:full:landing_page.html.twig
                    match:
                        Identifier\ContentType: [landing_page]
                folder:
                    controller: "tfktelemarkSkoleBundle:Folder:newsfolderViewEnhanced"
                    template: "tfktelemarkSkoleBundle:full:folder.html.twig"
                    match:
                        Identifier\ContentType: [folder]
                article:
                    template: tfktelemarkSkoleBundle:full:article.html.twig
                    match:
                        Identifier\ContentType: [article]
                article_shared:
                    template: tfktelemarkSkoleBundle:full:article.html.twig
                    match:
                        Identifier\ContentType: [article_shared]
                presentasjon:
                    controller: "tfktelemarkSkoleBundle:Folder:folderViewEnhanced"
                    template: tfktelemarkSkoleBundle:full:presentasjon.html.twig
                    match:
                        Identifier\ContentType: [presentasjon]
                presentasjon_shared:
                    controller: "tfktelemarkSkoleBundle:Folder:folderViewEnhanced"
                    template: tfktelemarkSkoleBundle:full:presentasjon.html.twig
                    match:
                        Identifier\ContentType: [presentasjon_shared]
                infobox:
                    template: tfktelemarkSkoleBundle:line:infobox.html.twig
                    match:
                        Identifier\ContentType: [infobox]
                embed_code:
                    template: tfktelemarkSkoleBundle:full:embed.html.twig
                    match:
                        Identifier\ContentType: [embed_code]
                spacer:
                    template: tfktelemarkSkoleBundle:full:spacer.html.twig
                    match:
                        Identifier\ContentType: [spacer]
                link:
                    template: tfktelemarkSkoleBundle:full:link.html.twig
                    match:
                        Identifier\ContentType: [link]
            line:
                article:
                    template: tfktelemarkSkoleBundle:line:article.html.twig
                    match:
                        Identifier\ContentType: [article]
                article_shared:
                    template: tfktelemarkSkoleBundle:line:article.html.twig
                    match:
                        Identifier\ContentType: [article_shared]
                spacer:
                    template: tfktelemarkSkoleBundle:line:spacer.html.twig
                    match:
                        Identifier\ContentType: [spacer]
                infobox:
                    template: tfktelemarkSkoleBundle:line:infobox.html.twig
                    match:
                        Identifier\ContentType: [infobox]
                folder:
                    template: tfktelemarkSkoleBundle:line:folder.html.twig
                    match:
                        Identifier\ContentType: [folder]
                presentasjon:
                    template: tfktelemarkSkoleBundle:line:presentasjon.html.twig
                    match:
                        Identifier\ContentType: [presentasjon]
                presentasjon_shared:
                    template: tfktelemarkSkoleBundle:line:presentasjon.html.twig
                    match:
                        Identifier\ContentType: [presentasjon_shared]
                link:
                    template: tfktelemarkSkoleBundle:line:link.html.twig
                    match:
                        Identifier\ContentType: [link]
                embed_code:
                    template: tfktelemarkSkoleBundle:line:embed.html.twig
                    match:
                        Identifier\ContentType: [embed_code]
            embed:
                image:
                    template: tfktelemarkSkoleBundle:embed:image.html.twig
                    match:
                        Identifier\ContentType: [image]

                file:
                    template: tfktelemarkSkoleBundle:embed:file.html.twig
                    match:
                        Identifier\ContentType: [file]
                embed_code:
                    template: tfktelemarkSkoleBundle:embed:embed.html.twig
                    match:
                        Identifier\ContentType: [embed_code]
            menu_line:
                link:
                    template: tfktelemarkSkoleBundle:menu_line:link.html.twig
                    match:
                        Identifier\ContentType: [link]
                spacer:
                    template: tfktelemarkSkoleBundle:menu_line:spacer.html.twig
                    match:
                        Identifier\ContentType: [spacer]
            shortcut_line:
                link:
                    template: tfktelemarkSkoleBundle:shortcut_line:link.html.twig
                    match:
                        Identifier\ContentType: [link]

            search_line:
                folder:
                    template: "tfktelemarkSkoleBundle:search_line:folder.html.twig"
                    match:
                        Identifier\ContentType: [folder]
                article:
                    template: tfktelemarkSkoleBundle:search_line:article.html.twig
                    match:
                        Identifier\ContentType: [article]
                article_shared:
                    template: tfktelemarkSkoleBundle:search_line:article.html.twig
                    match:
                        Identifier\ContentType: [article_shared]


#        block_view:
#            ContentBox:
#                template: tfktelemarkSkoleBundle:block:contentbox.html.twig
#                match:
#                    Type: ContentBox
#            ContentGrid:
#                template: tfktelemarkSkoleBundle:block:contentgrid.html.twig
#                match:
#                    Type: ContentGrid
#            Campaign:
#                template: tfktelemarkSkoleBundle:block:campaign:html.twig
#                match:
#                    Type: Campaign

        location_view:
            float3:
                article:
                    template: "tfktelemarkSkoleBundle:float3:article.html.twig"
                    match:
                        Identifier\ContentType: [article]
            block_box:
                article:
                    template: tfktelemarkSkoleBundle:block_box:article.html.twig
                    match:
                        Identifier\ContentType: [article]
                folder:
                    template: tfktelemarkSkoleBundle:block_box:folder.html.twig
                    match:
                        Identifier\ContentType: [folder]
                link:
                    template: tfktelemarkSkoleBundle:block_box:link.html.twig
                    match:
                        Identifier\ContentType: [link]
                presentasjon:
                    template: tfktelemarkSkoleBundle:block_box:presentasjon.html.twig
                    match:
                        Identifier\ContentType: [presentasjon]
                presentasjon_shared:
                    template: tfktelemarkSkoleBundle:block_box:presentasjon.html.twig
                    match:
                        Identifier\ContentType: [presentasjon_shared]

#            aside:
#                folder:
#                    template: "tfktelemarkSkoleBundle:aside:folder.html.twig"
#                    match:
#                      Identifier\ContentType: [folder]
#            aside_sub:
#                folder:
#                    controller: "tfktelemarkSkoleBundle:Folder:showFolderListAsideView"
#                    template: "tfktelemarkSkoleBundle:aside_sub:folder.html.twig"
#                    match:
#                        Identifier\ContentType: [folder]

