parameters:

    topmenu.tfk_school_group.identifiers:
        - folder
        - link

    subitems.tfk_school_group.identifiers:
        - article
        - fag

    subitems.tfk_school_group.limit: 10

    subitems.tfk_school_group.newsfolder.columns: 10
    subitems.tfk_school_group.newsfolder.rows: 5
    subitems.tfk_school_group.newsfolder.identifiers:
        - article
        - fag

    sidebar.tfk_school_group.identifiers.right:
        - infobox

    search.tfk_school_group.limit: 10
    search.tfk_school_group.identifiers:
        - article
        - folder
        - fag

    head.vest_vgs.logo: 'vesttelemark_toplogo.png'
    head.vest_vgs.title: 'Vest-telemark videreg책ende skole'
    head.vest_vgs.meta_author: 'Vest-telemark videreg책ende skole'
    head.vest_vgs.meta_description: 'Vest-telemark videreg책ende skole er en fin skole'
    head.vest_vgs.meta_keywords: 'telemark videreg책ende skole'
