parameters:

    topmenu.tfk_school_group.identifiers:
        - folder
        - link

    subitems.tfk_school_group.identifiers:
        - article

    subitems.tfk_school_group.limit: 10

    subitems.tfk_school_group.newsfolder.columns: 3
    subitems.tfk_school_group.newsfolder.rows: 5
    subitems.tfk_school_group.newsfolder.identifiers:
        - article

    sidebar.tfk_school_group.identifiers.right:
        - infobox

    search.tfk_school_group.limit: 10
    search.tfk_school_group.identifiers:
        - article
        - folder

    head.school_demo.logo: 'vesttelemark_toplogo.png'
    head.school_demo.title: 'Vest-telemark videregående skole'
    head.school_demo.meta_author: 'Vest-telemark videregående skole'
    head.school_demo.meta_description: 'Vest-telemark videregående skole er en fin skole'
    head.school_demo.meta_keywords: 'telemark videregående skole'

    head.vest_vdg.logo: 'vesttelemark_toplogo.png'
    head.vest_vdg.title: 'Vest-telemark videregående skole'
    head.vest_vdg.meta_author: 'Vest-telemark videregående skole'
    head.vest_vdg.meta_description: 'Vest-telemark videregående skole er en fin skole'
    head.vest_vdg.meta_keywords: 'telemark videregående skole'

