parameters:

    topmenu.tfk_school_group.identifiers:
        - folder
        - link

    subitems.tfk_school_group.identifiers:
        - article
        - presentasjon

    subitems.tfk_school_group.limit: 10

    subitems.tfk_school_group.newsfolder.columns: 10
    subitems.tfk_school_group.newsfolder.rows: 5
    subitems.tfk_school_group.newsfolder.identifiers:
        - article
        - presentasjon

    sidebar.tfk_school_group.identifiers.right:
        - infobox

    search.tfk_school_group.limit: 10
    search.tfk_school_group.identifiers:
        - article
        - folder
        - presentasjon

    head.vest_vgs.logo: 'vesttelemark_toplogo.png'
    head.vest_vgs.title: 'Vest-telemark videregående skole'
    head.vest_vgs.meta_author: 'Vest-telemark videregående skole'
    head.vest_vgs.meta_description: 'Vest-telemark videregående skole er en fin skole'
    head.vest_vgs.meta_keywords: 'telemark videregående skole'

    head.admin.logo: 'vesttelemark_toplogo.png'
    head.admin.title: 'Vest-telemark videregående skole'
    head.admin.meta_author: 'Vest-telemark videregående skole'
    head.admin.meta_description: 'Vest-telemark videregående skole er en fin skole'
    head.admin.meta_keywords: 'telemark videregående skole'
