parameters:
    ews.global.timezone: 'Central Europe Standard Time'

    ews.tfk_school_group.common_calendar_name: 'Felles skolekalender'
    ews.tfk_school_group.calendar_id: 0

    ews.bamble.calendar_name: 'Bamble VGS'
    ews.bamble.calendar_id: 0

    ews.boe.calendar_name: 'Bø VGS'
    ews.boe.calendar_id: 0

    ews.hjalmarj.calendar_name: 'Hjalmar Johansen VGS'
    ews.hjalmarj.calendar_id: 0

    ews.kragero.calendar_name: 'Kragerø VGS'
    ews.kragero.calendar_id: 0

    ews.nome.calendar_name: 'Nome VGS'
    ews.nome.calendar_id: 0

    ews.notodden.calendar_name: 'Notodden VGS'
    ews.notodden.calendar_id: 0

    ews.porsgrunn.calendar_name: 'Porsgrunn VGS'
    ews.porsgrunn.calendar_id: 0

    ews.rjukan.calendar_name: 'Rjukan VGS'
    ews.rjukan.calendar_id: 0

    ews.skien.calendar_name: 'Skien VGS'
    ews.skien.calendar_id: 0

    ews.skogmo.calendar_name: 'Skogmo VGS'
    ews.skogmo.calendar_id: 0

    ews.vest_vgs.calendar_name: 'Vest Telemark VGS'
    ews.vest_vgs.calendar_id: 0

    ews.nettskolen.calendar_name: 'Notodden VGS'
    ews.nettskolen.calendar_id: 0

    ews.tfk_school_group.categories:
        - Skoleruta
        - Arrangement
        - Melding
        - Skole/hjem
        - Annet

    topmenu.tfk_school_group.identifiers:


    topmenu.tfk_school_group.identifiers_hide_from_menu:
        - folder
        - presentasjon
        - presentasjon_shared
        - embed_code
        - link
        - spacer

    subitems.tfk_school_group.identifiers:
        - article
        - article_shared
        - presentasjon
        - presentasjon_shared
        - embed_code
        - spacer
        - link

    subitems.tfk_school_group.limit: 40

    subitems.tfk_school_group.newsfolder.columns: 40
    subitems.tfk_school_group.newsfolder.rows: 5
    subitems.tfk_school_group.newsfolder.identifiers:
        - article
        - article_shared
        - presentasjon
        - presentasjon_shared
        - spacer
        - person
        - link

    sidebar.tfk_school_group.identifiers.right:
        - infobox

    search.tfk_school_group.limit: 40
    search.tfk_school_group.identifiers:
        - article
        - article_shared
        - folder
        - presentasjon
        - presentasjon_shared
        - embed_code

    head.vest_vgs.logo: 'logo-vest-telemark-vgs-rgb.svg'
    head.vest_vgs.title: 'Vest-Telemark vidaregåande skule'
    head.vest_vgs.meta_author: 'Vest-Telemark vidaregåande skule'
    head.vest_vgs.meta_description: 'Vest-Telemark vidaregåande skule'
    head.vest_vgs.meta_keywords: 'vest telemark videregående skule'

    footer.vest_vgs.email: 'vesttelemark.vgs@vtfk.no'
    footer.vest_vgs.phone: 'Sentralbord Dalen: 35 91 97 00'
    footer.vest_vgs.phone2: 'Sentralbord Seljord: 35 91 90 70'
    footer.vest_vgs.post: 'Postboks 2844, 3702 Skien'
    footer.vest_vgs.adress: 'Storvegen 195 3880 Dalen'
    footer.vest_vgs.adress2: 'Brøløsvegen 2 3840 Seljord'
    footer.vest_vgs.contact: 'Webmaster'
    footer.vest_vgs.link: 'http://apps.t-fk.no/ansatte/#/ansatt/2703'
    footer.vest_vgs.contactlink: "https://www.vtfk.no/meny/om-oss/kontakt-oss/ansattoversikt?avd=vest-telemark%20vidareg%C3%A5ande%20skule"
    footer.vest_vgs.fb: 'Dalen på facebook'
    footer.vest_vgs.fblink: 'http://www.facebook.com/VTVGS'
    footer.vest_vgs.fb2: 'Seljord på facebook'
    footer.vest_vgs.fblink2: 'https://www.facebook.com/seljordvgs?fref=ts'
    footer.vest_vgs.google: MxG6p7VzM_W0hL2qufvSYx0iJDfnlfnDBc_cEy__fl4

    head.telemark.logo: 'telemark.svg'
    head.telemark.title: 'Telemark Fylkeskommune'
    head.telemark.meta_author: 'Telemark Fylkeskommune'
    head.telemark.meta_description: 'Modig, imøtekommende og troverdig'
    head.telemark.meta_keywords: 'admin telemark videregående skole'
    #footer.telemark.analytics: 'UA-91276641-1'

    footer.telemark.email: ' post@vtfk.no'
    footer.telemark.phone: '35 91 70 00'
    footer.telemark.phone2: '35 91 70 01'
    footer.telemark.post: 'Postboks 2844, 3702 Skien'
    footer.telemark.adress: 'Fylkesbakken 10, 3715 Skien'
    footer.telemark.contact: 'Webmaster'
    footer.telemark.link: 'http://apps.t-fk.no/ansatte/'
    footer.telemark.fblink: 'https://www.facebook.com/telemarkfylke'
    footer.telemark.fb: 'Facebook'
    footer.telemark.analytics: 'UA-5569947-5'


    head.site.logo: 'admin_toplogo.png'
    head.site.title: 'Admin videregående skole'
    head.site.meta_author: 'Admin videregående skole'
    head.site.meta_description: 'Modig, imøtekommende og troverdig'
    head.site.meta_keywords: 'admin telemark videregående skole'
    footer.site.analytics: 'UA-91276641-1'

    head.bamble.logo: 'logo-bamble-vgs-rgb.svg'
    head.bamble.title: 'Bamble videregående skole'
    head.bamble.meta_author: 'Bamble videregående skole'
    head.bamble.meta_description: 'Bamble videregående skole- det er hos oss det begynne'
    head.bamble.meta_keywords: ''

    footer.bamble.email: 'bamble.vgs@vtfk.no'
    footer.bamble.phone: 'Avd. Grasmyr tlf 35 91 94 00'
    footer.bamble.phone2: 'Avd. Croftholmen tlf 35 91 79 00'
    footer.bamble.post: 'Postboks 2844, 3702 Skien'
    footer.bamble.adress: 'Avd. Grasmyr: Tønderveien 6, 3961 Stathelle'
    footer.bamble.adress2: 'Avd. Croftholmen: Tostrupsvei, 3960 Stathelle'
    footer.bamble.contact: 'Webmaster'
    footer.bamble.link: 'http://apps.t-fk.no/ansatte/#/ansatt/353'
    footer.bamble.contactlink: "https://www.vtfk.no/meny/om-oss/kontakt-oss/ansattoversikt?avd=bamble%20videreg%C3%A5ende%20skole"
    footer.bamble.fblink: 'https://www.facebook.com/bamblevgs/'
    footer.bamble.fb: 'Bamble på facebook'
    footer.bamble.instagram: 'https://www.instagram.com/bamblevgs/'
    footer.bamble.youtube: 'https://www.youtube.com/channel/UC49syS4LRCmbIA5K6bLFk7g'
    footer.bamble.analytics: 'UA-5569947-5'

    head.boe.logo: 'logo-boe-vgs-rgb.svg'
    head.boe.title: 'Bø vidaregåande skule'
    head.boe.meta_author: 'Bø Vidaregåande skule'
    head.boe.meta_description: 'Bø Vidaregåande er ein fin skule'
    head.boe.meta_keywords: 'Bø Vidaregåande skule'

    footer.boe.email: 'bo.vgs@vtfk.no'
    footer.boe.phone: '35 91 90 00'
    footer.boe.post: 'Postboks 54, 3833 Bø i Telemark'
    footer.boe.adress: 'Gymnasbakken 23, Bø i Telemark'
    footer.boe.contact: 'Webmaster'
    footer.boe.link: 'http://apps.t-fk.no/ansatte/#/ansatt/20169'
    footer.boe.contactlink: "https://www.vtfk.no/meny/om-oss/kontakt-oss/ansattoversikt?avd=b%C3%B8%20vidareg%C3%A5ande%20skule"
    footer.boe.fblink: 'https://www.facebook.com/BØ-Vidaregåande-Skule-530119240390044/'
    footer.boe.fb: 'Facebook'
    footer.boe.analytics: 'UA-107696217-1'

    head.hjalmarj.logo: 'logo-hjalmar-johansen-vgs-rgb.svg'
    head.hjalmarj.title: 'Hjalmar Johansen videregående skole'
    head.hjalmarj.meta_author: 'Hjalmar Johansen videregående skole'
    head.hjalmarj.meta_description: 'faglig sosial utvikling'
    head.hjalmarj.meta_keywords: 'hjalmar johansen videregående skole'

    footer.hjalmarj.email: 'hjalmarjohansen.vgs@vtfk.no'
    footer.hjalmarj.phone: '35 91 83 00'
    footer.hjalmarj.post: 'Postboks 2844, 3702 Skien'
    footer.hjalmarj.adress: 'Moflatvegen 38, 3733 Skien'
    footer.hjalmarj.contact: 'Webmaster'
    footer.hjalmarj.link: 'http://apps.t-fk.no/ansatte/#/ansatt/2141'
    footer.hjalmarj.contactlink: "https://www.vtfk.no/meny/om-oss/kontakt-oss/ansattoversikt?avd=hjalmar%20johansen%20videreg%C3%A5ende%20skole"
    footer.hjalmarj.fblink: 'http://www.facebook.com/pages/Hjalmar-Johansen-Videregående-Skole/324566620918967'
    footer.hjalmarj.fb: 'Facebook'
    footer.hjalmarj.instagram: 'https://instagram.com/explore/tags/hjalmarjohansenvgs/'
    footer.hjalmarj.twitter: 'https://twitter.com/hjalmarjovgs'
    footer.hjalmarj.analytics: 'UA-6487573-1'

    head.kragero.logo: 'logo-kragero-vgs-rgb.svg'
    head.kragero.title: 'Kragerø videregående skole'
    head.kragero.meta_author: 'Kragerø videregående skole'
    head.kragero.meta_description: 'Kragerø videregående skole er en fin skole'
    head.kragero.meta_keywords: 'kragerø videregående skole'

    footer.kragero.email: 'kragero.vgs@vtfk.no'
    footer.kragero.phone: '35 91 95 00'
    footer.kragero.post: 'Frydenborgveien 9–11, 3772 Kragerø'
    footer.kragero.adress: 'Frydenborgveien 9–11, Kragerø'
    footer.kragero.contact: 'Webmaster'
    footer.kragero.link: 'http://apps.t-fk.no/ansatte/#/ansatt/13407'
    footer.kragero.contactlink: "https://www.vtfk.no/meny/om-oss/kontakt-oss/ansattoversikt?avd=krager%C3%B8%20videreg%C3%A5ende%20skole"
    footer.kragero.fblink: 'https://www.facebook.com/kragerovgs?fref=ts'
    footer.kragero.fb: 'Facebook'
    footer.kragero.analytics: 'UA-92067423-1'

    head.nome.logo: 'logo-nome-vgs-rgb.svg'
    head.nome.title: 'Nome videregående skole'
    head.nome.meta_author: 'Nome videregående skole'
    head.nome.meta_description: 'Nome videregående skole er en fin skole'
    head.nome.meta_keywords: 'nome videregående skole'

    footer.nome.email: 'nome.vgs@vtfk.no'
    footer.nome.phone: 'Sentralbord Søve: 35 91 87 00'
    footer.nome.phone2: 'Sentralbord Lunde: 35 91 88 00'
    footer.nome.post: ' Søvevegen 12, 3830 Ulefoss'
    footer.nome.adress: 'Avd. Søve: Søvevegen 12, Ulefoss'
    footer.nome.adress2: 'Avd. Lunde: Olav strannasvei 25, 3825 Lunde'
    footer.nome.contact: 'Webmaster'
    footer.nome.link: 'http://apps.t-fk.no/ansatte/#/ansatt/25065'
    footer.nome.contactlink: "https://www.vtfk.no/meny/om-oss/kontakt-oss/ansattoversikt?avd=nome%20videreg%C3%A5ende%20skole"
    footer.nome.fblink: 'https://www.facebook.com/pages/Nome-videregående-avdeling-Lunde/345003742340399?fref=ts'
    footer.nome.fb: 'Avdeling Lunde på facebook'
    footer.nome.fblink2: 'https://www.facebook.com/pages/Nome-videregående-avdeling-Søve/300477916812929?fref=ts'
    footer.nome.fb2: 'Avdeling Søve på facebook'
    footer.nome.youtube: 'https://www.youtube.com/channel/UCd-NJgMguoKiubhS5e9w1Jg/videos'
    footer.nome.analytics: 'UA-92091324-1'

    head.notodden.logo: 'logo-notodden-vgs-rgb.svg'
    head.notodden.title: 'Notodden videregående skole'
    head.notodden.meta_author: 'Notodden videregående skole'
    head.notodden.meta_description: 'Notodden videregående skole er en fin skole'
    head.notodden.meta_keywords: 'notodden videregående skole'

    footer.notodden.email: 'notodden.vgs@vtfk.no'
    footer.notodden.phone: '35 91 85 00'
    footer.notodden.post: 'Postboks 184, 3672 Notodden'
    footer.notodden.adress: 'Heddalsvegen 4, Notodden'
    footer.notodden.contact: 'Webmaster'
    footer.notodden.link: 'http://apps.t-fk.no/ansatte/#/ansatt/17171'
    footer.notodden.contactlink: "https://www.vtfk.no/meny/om-oss/kontakt-oss/ansattoversikt?avd=notodden%20videreg%C3%A5ende%20skole"
    footer.notodden.fblink: 'https://www.facebook.com/NotoddenVideregaendeSkole/'
    footer.notodden.fb: 'Facebook'

    head.porsgrunn.logo: 'logo-porsgrunn-vgs-rgb.svg'
    head.porsgrunn.title: 'Porsgrunn videregående skole'
    head.porsgrunn.meta_author: 'Porsgrunn videregående skole'
    head.porsgrunn.meta_description: 'Sammen om mestring, mangfold og miljø!'
    head.porsgrunn.meta_keywords: 'porsgrunn videregående skole'

    footer.porsgrunn.email: 'porsgrunn.vgs@vtfk.no'
    footer.porsgrunn.phone: '35 91 75 00'
    footer.porsgrunn.post: 'Postboks 2844, 3702 Skien'
    footer.porsgrunn.adress: 'Avd. Nord: Kjølnes Ring 58, 3918 Porsgrunn'
    footer.porsgrunn.adress2: 'Avd. Sør: Kjølnes Ring 20, 3918 Porsgrunn'
    footer.porsgrunn.contact: 'Webmaster'
    footer.porsgrunn.link: 'http://apps.t-fk.no/ansatte/#/ansatt/13462'
    footer.porsgrunn.contactlink: "https://www.vtfk.no/meny/om-oss/kontakt-oss/ansattoversikt?avd=porsgrunn%20videreg%C3%A5ende%20skole"
    footer.porsgrunn.fblink: 'https://www.facebook.com/PorsgrunnVGS/'
    footer.porsgrunn.fb: 'Facebook'
    footer.porsgrunn.twitter: 'https://twitter.com/PorsgrunnVGS'
    footer.porsgrunn.instagram: 'https://www.instagram.com/porsgrunnvgs/'
    footer.porsgrunn.flickr: 'https://www.flickr.com/photos/porvgs/albums'
    footer.porsgrunn.analytics: 'UA-47841095-1'
    # footer.porsgrunn.surveymonkey: 'tRaiETqnLgj758hTBazgd8FDSSK_2BdJwgb90HhEfWcrT_2FO1oWc7dLEAI8ieHZ_2B8tr'

    head.rjukan.logo: 'logo-rjukan-vgs-rgb.svg'
    head.rjukan.title: 'Rjukan videregående skole'
    head.rjukan.meta_author: 'Rjukan videregående skole'
    head.rjukan.meta_description: 'Rjukan videregående skole - En skole for alle'
    head.rjukan.meta_keywords: 'rjukan videregående skole'

    footer.rjukan.email: 'rjukan.vgs@vtfk.no'
    footer.rjukan.phone: '35 91 99 00'
    footer.rjukan.post: 'Såheimsveien 22, 3660 Rjukan'
    footer.rjukan.adress: 'Såheimsveien 22, Rjukan'
    footer.rjukan.contact: 'Webmaster'
    footer.rjukan.link: 'http://apps.t-fk.no/ansatte/#/ansatt/21646'
    footer.rjukan.contactlink: "https://www.vtfk.no/meny/om-oss/kontakt-oss/ansattoversikt?avd=rjukan%20videreg%C3%A5ende%20skole"
    footer.rjukan.fblink: 'http://www.facebook.com/rjukanvgs/'
    footer.rjukan.fb: 'Facebook'

    head.skien.logo: 'logo-skien-vgs-rgb.svg'
    head.skien.title: 'Skien videregående skole'
    head.skien.meta_author: 'Skien videregående skole'
    head.skien.meta_description: 'Skien videregående skole er en fin skole'
    head.skien.meta_keywords: 'skien videregående skole'

    footer.skien.email: 'skien.vgs@vtfk.no'
    footer.skien.phone: 'Telefon: 35 91 80 00'
    footer.skien.post: 'Postboks 2844, 3702 Skien'
    footer.skien.adress: 'Hollenderigata 5, 3732 Skien'

    footer.skien.contact: 'Webmaster'
    footer.skien.link: 'http://apps.t-fk.no/ansatte/#/ansatt/11165'
    footer.skien.contactlink: "https://www.vtfk.no/meny/om-oss/kontakt-oss/ansattoversikt?avd=skien%20videreg%C3%A5ende%20skole"
    footer.skien.fblink: 'https://www.facebook.com/skienvgs/'
    footer.skien.fb: 'Facebook'
    footer.skien.youtube: 'https://www.youtube.com/channel/UCSaA2KXfm__BkVYb49P2ACg'
    footer.skien.analytics: 'UA-56306666-1'

    head.skogmo.logo: 'logo-skogmo-vgs-rgb.svg'
    head.skogmo.title: 'Skogmo videregående skole'
    head.skogmo.meta_author: 'Skogmo videregående skole'
    head.skogmo.meta_description: 'Skogmo videregående skole er en fin skole'
    head.skogmo.meta_keywords: 'skogmo'

    footer.skogmo.email: 'skogmo.vgs@vtfk.no'
    footer.skogmo.phone: '35 91 92 00'
    footer.skogmo.post: 'Postboks 2844, 3702 Skien'
    footer.skogmo.adress: 'Kjørbekkdalen 11, Skien'
    footer.skogmo.contact: 'Webmaster'
    footer.skogmo.link: 'http://apps.t-fk.no/ansatte/#/ansatt/8491'
    footer.skogmo.contactlink: "https://www.vtfk.no/meny/om-oss/kontakt-oss/ansattoversikt?avd=skogmo%20videreg%C3%A5ende%20skole"
    footer.skogmo.fblink: 'https://www.facebook.com/Skogmovgs/'
    footer.skogmo.fb: 'Facebook'

    head.fagskolen.logo: 'fagskolen_toplogo.svg'
    head.fagskolen.title: 'Fagskolen telemark'
    head.fagskolen.meta_author: 'Fagskolen telemark'
    head.fagskolen.meta_description: 'Fagskolen telemark er en fin skole'
    head.fagskolen.meta_keywords: 'fagskolen telemark'

    footer.fagskolen.email: 'post@fagskolentelemark.no'
    footer.fagskolen.phone: '35 91 77 50'
    footer.fagskolen.post: 'Postboks 2844, 3702 Skien'
    footer.fagskolen.adress: 'Kjølnes Ring 26, 3918 Porsgrunn'
    footer.fagskolen.contact: 'Webmaster'
    footer.fagskolen.link: 'http://apps.t-fk.no/ansatte/#/ansatt/11922'
    footer.fagskolen.fblink: 'https://www.facebook.com/FagskolenTelemark?ref=hl'
    footer.fagskolen.fb: 'Facebook'
    footer.fagskolen.twitter: 'https://twitter.com/fagskolen'
    footer.fagskolen.youtube: 'https://www.youtube.com/channel/UC9eKxv7J1hc2iKCMGSg6kQg'
    footer.fagskolen.flickr: 'https://www.flickr.com/photos/107959030@N03/albums/with/72157654237948960'
    footer.fagskolen.linkedin: 'https://www.linkedin.com/company/fagskolen-telemark'
    footer.fagskolen.analytics: 'UA-37031548-7'

    head.nettskolen.logo: 'nettskolen_toplogo.png'
    head.nettskolen.title: 'Nettskolen Telemark'
    head.nettskolen.meta_author: 'Nettskolen Telemark'
    head.nettskolen.meta_keywords: 'nettskolen, telemark'
    footer.nettskolen.email: 'post@nrs.tm.no'
    footer.nettskolen.phone: 'Sentralbord: 35 91 86 00'
    footer.nettskolen.post: '3674 NOTODDEN'
    footer.nettskolen.adress: 'Heddalsveien 4 3674 NOTODDEN'
    footer.nettskolen.fb: 'Facebook'
    footer.nettskolen.fblink: 'https://www.facebook.com/notoddenressurssenter/'
