parameters:

    topmenu.tfk_school_group.identifiers:
        - folder
        - link

    subitems.tfk_school_group.identifiers:
        - article
        - presentasjon
        - presentasjon_shared
        - embed_code
    topmenu.tfk_school_group.identifiers_hide_from_menu:
          - folder
          - presentasjon
          - presentasjon_shared
          - embed_code
    subitems.tfk_school_group.limit: 10

    subitems.tfk_school_group.newsfolder.columns: 10
    subitems.tfk_school_group.newsfolder.rows: 5
    subitems.tfk_school_group.newsfolder.identifiers:
        - article
        - presentasjon
        - presentasjon_shared

    sidebar.tfk_school_group.identifiers.right:
        - infobox

    search.tfk_school_group.limit: 10
    search.tfk_school_group.identifiers:
        - article
        - folder
        - presentasjon
        - presentasjon_shared
        - embed_code

    head.vest_vgs.logo: 'vesttelemark_toplogo.png'
    head.vest_vgs.title: 'Vest-telemark videregående skole'
    head.vest_vgs.meta_author: 'Vest-telemark videregående skole'
    head.vest_vgs.meta_description: 'Vest-telemark videregående skole er en fin skole'
    head.vest_vgs.meta_keywords: 'telemark videregående skole'

    head.admin.logo: 'admin_toplogo.png'
    head.admin.title: 'Vest-telemark videregående skole'
    head.admin.meta_author: 'Vest-telemark videregående skole'
    head.admin.meta_description: 'Vest-telemark videregående skole er en fin skole'
    head.admin.meta_keywords: 'telemark videregående skole'

    head.bamble.logo: 'bamble_toplogo.png'
    head.bamble.title: 'Bamble videregående skole'
    head.bamble.meta_author: 'Bamble videregående skole'
    head.bamble.meta_description: 'Bamble videregående skole videregående skole er en fin skole'
    head.bamble.meta_keywords: 'bamble videregående skole'

    head.boe.logo: 'boe_toplogo.png'
    head.boe.title: 'Bøe videregående skole'
    head.boe.meta_author: 'Bamble videregående skole'
    head.boe.meta_description: 'Bamble videregående skole videregående skole er en fin skole'
    head.boe.meta_keywords: 'bamble videregående skole'

    head.hjalmarj.logo: 'hjalmarj_toplogo.png'
    head.hjalmarj.title: 'Hjalmar Johansen videregående skole'
    head.hjalmarj.meta_author: 'Hjalmar Johansen videregående skole'
    head.hjalmarj.meta_description: 'Hjalmar Johansen videregående skole er en fin skole'
    head.hjalmarj.meta_keywords: 'hjalmar johansen videregående skole'

    head.kragero.logo: 'kragero_toplogo.png'
    head.kragero.title: 'Kragerø videregående skole'
    head.kragero.meta_author: 'Kragerø videregående skole'
    head.kragero.meta_description: 'Kragerø videregående skole er en fin skole'
    head.kragero.meta_keywords: 'kragerø videregående skole'

    head.nome.logo: 'nome_toplogo.png'
    head.nome.title: 'Nome videregående skole'
    head.nome.meta_author: 'Nome videregående skole'
    head.nome.meta_description: 'Nome videregående skole er en fin skole'
    head.nome.meta_keywords: 'nome videregående skole'

    head.notodden.logo: 'notodden_toplogo.png'
    head.notodden.title: 'Notodden videregående skole'
    head.notodden.meta_author: 'Notodden videregående skole'
    head.notodden.meta_description: 'Notodden videregående skole er en fin skole'
    head.notodden.meta_keywords: 'notodden videregående skole'

    head.porsgrunn.logo: 'porsgrunn_toplogo.png'
    head.porsgrunn.title: 'Porsgrunn videregående skole'
    head.porsgrunn.meta_author: 'Porsgrunn videregående skole'
    head.porsgrunn.meta_description: 'Porsgrunn videregående skole er en fin skole'
    head.porsgrunn.meta_keywords: 'porsgrunn videregående skole'

    head.rjukan.logo: 'rjukan_toplogo.png'
    head.rjukan.title: 'Rjukan videregående skole'
    head.rjukan.meta_author: 'Rjukan videregående skole'
    head.rjukan.meta_description: 'Rjukan videregående skole er en fin skole'
    head.rjukan.meta_keywords: 'rjukan videregående skole'

    head.skien.logo: 'skien_toplogo.png'
    head.skien.title: 'Skien videregående skole'
    head.skien.meta_author: 'Skien videregående skole'
    head.skien.meta_description: 'Skien videregående skole er en fin skole'
    head.skien.meta_keywords: 'skien videregående skole'

    head.skogmo.logo: 'skogmo_toplogo.png'
    head.skogmo.title: 'Skogmo videregående skole'
    head.skogmo.meta_author: 'Skogmo videregående skole'
    head.skogmo.meta_description: 'Skogmo videregående skole er en fin skole'
    head.skogmo.meta_keywords: 'skogmo videregående skole'

    head.fagskolen.logo: 'fagskolen_toplogo.png'
    head.fagskolen.title: 'Fagskolen telemark'
    head.fagskolen.meta_author: 'Fagskolen telemark'
    head.fagskolen.meta_description: 'Fagskolen telemark er en fin skole'
    head.fagskolen.meta_keywords: 'fagskolen videregående skole'