parameters:

    topmenu.tfk_school_group.identifiers:
        - spacer

    topmenu.tfk_school_group.identifiers_hide_from_menu:
        - folder
        - presentasjon
        - presentasjon_shared
        - embed_code
        - link

    subitems.tfk_school_group.identifiers:
        - article
        - article_shared
        - presentasjon
        - presentasjon_shared
        - embed_code
        - spacer
        - link

    subitems.tfk_school_group.limit: 40

    subitems.tfk_school_group.newsfolder.columns: 40
    subitems.tfk_school_group.newsfolder.rows: 5
    subitems.tfk_school_group.newsfolder.identifiers:
        - article
        - article_shared
        - presentasjon
        - presentasjon_shared
        - spacer

    sidebar.tfk_school_group.identifiers.right:
        - infobox

    search.tfk_school_group.limit: 40
    search.tfk_school_group.identifiers:
        - article
        - article_shared
        - folder
        - presentasjon
        - presentasjon_shared
        - embed_code

    head.vest_vgs.logo: 'vesttelemark_toplogo.png'
    head.vest_vgs.title: 'Vest-telemark videregående skole'
    head.vest_vgs.meta_author: 'Vest-telemark videregående skole'
    head.vest_vgs.meta_description: 'Vest-telemark videregående skole er en fin skole'
    head.vest_vgs.meta_keywords: 'telemark videregående skole'

    footer.vest_vgs.email: 'vest-telemark.vgs@t-fk.no'
    footer.vest_vgs.phone: 'Sentralbord Dalen: 35 91 97 00'
    footer.vest_vgs.phone2: 'Sentralbord Seljord: 35 91 90 70'
    footer.vest_vgs.post: 'Postboks 2844, 3702 Skien'
    footer.vest_vgs.adress: 'Storvegen 195 3880 Dalen'
    footer.vest_vgs.adress2: 'Brøløsvegen 2 3840 Seljord'
    footer.vest_vgs.contact: 'Webmaster'
    footer.vest_vgs.link: 'http://apps.t-fk.no/ansatte/#/ansatt/2703'
    footer.vest_vgs.fb: 'Dalen på facebook'
    footer.vest_vgs.fblink: 'http://www.facebook.com/VTVGS'
    footer.vest_vgs.fb2: 'Seljord på facebook'
    footer.vest_vgs.fblink2: 'https://www.facebook.com/seljordvgs?fref=ts'

    head.admin.logo: 'admin_toplogo.png'
    head.admin.title: 'Admin videregående skole'
    head.admin.meta_author: 'Admin videregående skole'
    head.admin.meta_description: 'Modig, imøtekommende og troverdig'
    head.admin.meta_keywords: 'admin telemark videregående skole'

    head.bamble.logo: 'bamble_toplogo.png'
    head.bamble.title: 'Bamble videregående skole'
    head.bamble.meta_author: 'Bamble videregående skole'
    head.bamble.meta_description: 'Bamble videregående skole- det er hos oss det begynne'
    head.bamble.meta_keywords: 'http://apps.t-fk.no/ansatte/#/ansatt/353'

    footer.bamble.email: 'bamble.vgs@t-fk.no'
    footer.bamble.phone: 'Avd.Grasmyr tlf 35 91 94 00'
    footer.bamble.phone2: 'Avd.Croftholmen tlf 35 91 79 00'
    footer.bamble.post: 'Postboks 2844, 3702 Skien'
    footer.bamble.adress: 'Tønderveien 6 , 3961 STATHELLE'
    footer.bamble.adress2: 'Tostrupsvei, 3960 STATHELLE'
    footer.bamble.contact: 'Webmaster'
    footer.bamble.link: 'http://apps.t-fk.no/ansatte/#/ansatt/353'
    footer.bamble.fblink: 'https://www.facebook.com/bamblevgs/'
    footer.bamble.fb: 'Bamble på facebook'
    footer.bamble.instagram: 'https://www.instagram.com/bamblevgs/'
    footer.bamble.youtube: 'https://www.youtube.com/channel/UC49syS4LRCmbIA5K6bLFk7g'

    head.boe.logo: 'boe_toplogo.png'
    head.boe.title: 'Bø vidargåande skole'
    head.boe.meta_author: 'Bø Vidargåande skole'
    head.boe.meta_description: 'Bø Vidargåande skole er en fin skole'
    head.boe.meta_keywords: 'Bø Vidargåande skole'

    footer.boe.email: 'bo.vgs@t-fk.no'
    footer.boe.phone: '35 91 90 00'
    footer.boe.post: 'Postboks 54, 3833 Bø i Telemark'
    footer.boe.adress: 'Gymnasbakken 23, Bø i Telemark'
    footer.boe.contact: 'Webmaster'
    footer.boe.link: 'http://apps.t-fk.no/ansatte/#/ansatt/20169'
    footer.boe.fblink: 'https://www.facebook.com/BØ-Vidaregåande-Skule-530119240390044/'
    footer.boe.fb: 'Facebook'

    head.hjalmarj.logo: 'hjalmarj_toplogo.png'
    head.hjalmarj.title: 'Hjalmar Johansen videregående skole'
    head.hjalmarj.meta_author: 'Hjalmar Johansen videregående skole'
    head.hjalmarj.meta_description: 'faglig sosial utvikling'
    head.hjalmarj.meta_keywords: 'hjalmar johansen videregående skole'

    footer.hjalmarj.email: 'hjalmarjohansen.vgs@t-fk.no'
    footer.hjalmarj.phone: '35 91 83 00'
    footer.hjalmarj.post: 'Postboks 2844, 3702 Skien'
    footer.hjalmarj.adress: 'Moflatvegen 38, 3733 Skien'
    footer.hjalmarj.contact: 'Webmaster'
    footer.hjalmarj.link: 'http://apps.t-fk.no/ansatte/#/ansatt/2141'
    footer.hjalmarj.fblink: 'http://www.facebook.com/pages/Hjalmar-Johansen-Videregående-Skole/324566620918967'
    footer.hjalmarj.fb: 'Facebook'
    footer.hjalmarj.instagram: 'https://instagram.com/explore/tags/hjalmarjohansenvgs/'
    footer.hjalmarj.twitter: 'https://twitter.com/hjalmarjovgs'

    head.kragero.logo: 'kragero_toplogo.png'
    head.kragero.title: 'Kragerø videregående skole'
    head.kragero.meta_author: 'Kragerø videregående skole'
    head.kragero.meta_description: 'Kragerø videregående skole er en fin skole'
    head.kragero.meta_keywords: 'kragerø videregående skole'

    footer.kragero.email: 'kragero.vgs@t-fk.no'
    footer.kragero.phone: '35 91 95 00'
    footer.kragero.post: 'Frydenborgveien 9–11, 3772 Kragerø'
    footer.kragero.adress: 'Frydenborgveien 9–11, Kragerø'
    footer.kragero.contact: 'Webmaster'
    footer.kragero.link: 'http://apps.t-fk.no/ansatte/#/ansatt/13407'
    footer.kragero.fblink: 'https://www.facebook.com/kragerovgs?fref=ts'
    footer.kragero.fb: 'Facebook'

    head.nome.logo: 'nome_toplogo.png'
    head.nome.title: 'Nome videregående skole'
    head.nome.meta_author: 'Nome videregående skole'
    head.nome.meta_description: 'Nome videregående skole er en fin skole'
    head.nome.meta_keywords: 'nome videregående skole'

    footer.nome.email: 'nome.vgs@t-fk.no'
    footer.nome.phone: '35 91 87 00'
    footer.nome.post: ' Søvevegen 12, 3830 Ulefoss'
    footer.nome.adress: 'Søvevegen 12, Ulefoss'
    footer.nome.contact: 'Webmaster'
    footer.nome.link: 'http://apps.t-fk.no/ansatte/#/ansatt/17714'
    footer.nome.fblink: 'https://www.facebook.com/pages/Nome-videregående-avdeling-Lunde/345003742340399?fref=ts'
    footer.nome.fb: 'Lunde VGS på facebook'
    footer.nome.fblink2: 'https://www.facebook.com/pages/Nome-videregående-avdeling-Søve/300477916812929?fref=ts'
    footer.nome.fb2: 'Søve VGS på facebook'
    footer.nome.youtube: 'https://www.youtube.com/channel/UCd-NJgMguoKiubhS5e9w1Jg/videos'

    head.notodden.logo: 'notodden_toplogo.png'
    head.notodden.title: 'Notodden videregående skole'
    head.notodden.meta_author: 'Notodden videregående skole'
    head.notodden.meta_description: 'Notodden videregående skole er en fin skole'
    head.notodden.meta_keywords: 'notodden videregående skole'

    footer.notodden.email: 'notodden.vgs@t-fk.no'
    footer.notodden.phone: '35 91 85 00'
    footer.notodden.post: 'Postboks 184, 3672 Notodden'
    footer.notodden.adress: 'Heddalsvegen 4, Notodden'
    footer.notodden.contact: 'Webmaster'
    footer.notodden.link: 'http://apps.t-fk.no/ansatte/#/ansatt/17171'
    footer.notodden.fblink: 'https://www.facebook.com/NotoddenVideregaendeSkole/'
    footer.notodden.fb: 'Facebook'

    head.porsgrunn.logo: 'porsgrunn_toplogo.png'
    head.porsgrunn.title: 'Porsgrunn videregående skole'
    head.porsgrunn.meta_author: 'Porsgrunn videregående skole'
    head.porsgrunn.meta_description: 'Sammen om mestring, mangfold og miljø!'
    head.porsgrunn.meta_keywords: 'porsgrunn videregående skole'

    footer.porsgrunn.email: 'porsgrunn.vgs@t-fk.no'
    footer.porsgrunn.phone: '35 91 75 00'
    footer.porsgrunn.post: 'Postboks 2844, 3702 Skien'
    footer.porsgrunn.adress: 'Kjølnes Ring 58, 3918 Porsgrunn'
    footer.porsgrunn.adress2: 'Kjølnes Ring 20, 3918 Porsgrunn'
    footer.porsgrunn.contact: 'Webmaster'
    footer.porsgrunn.link: 'http://apps.t-fk.no/ansatte/#/ansatt/13462'
    footer.porsgrunn.fblink: 'https://www.facebook.com/PorsgrunnVGS/'
    footer.porsgrunn.fb: 'Facebook'
    footer.porsgrunn.twitter: 'https://twitter.com/PorsgrunnVGS'
    footer.porsgrunn.instagram: 'https://www.instagram.com/porsgrunnvgs/'
    footer.porsgrunn.flickr: 'https://www.flickr.com/photos/porvgs/albums'

    head.rjukan.logo: 'rjukan_toplogo.png'
    head.rjukan.title: 'Rjukan videregående skole'
    head.rjukan.meta_author: 'Rjukan videregående skole'
    head.rjukan.meta_description: 'Rjukan videregående skole - En skole for alle'
    head.rjukan.meta_keywords: 'rjukan videregående skole'

    footer.rjukan.email: 'rjukan.vgs@t-fk.no'
    footer.rjukan.phone: '35 91 99 00'
    footer.rjukan.post: 'Såheimsveien 22, 3660 Rjukan'
    footer.rjukan.adress: 'Såheimsveien 22, Rjukan'
    footer.rjukan.contact: 'Webmaster'
    footer.rjukan.link: 'http://apps.t-fk.no/ansatte/#/ansatt/1186'
    footer.rjukan.fblink: 'http://www.facebook.com/rjukanvgs/'
    footer.rjukan.fb: 'Facebook'

    head.skien.logo: 'skien_toplogo.png'
    head.skien.title: 'Skien videregående skole'
    head.skien.meta_author: 'Skien videregående skole'
    head.skien.meta_description: 'Skien videregående skole er en fin skole'
    head.skien.meta_keywords: 'skien videregående skole'

    footer.skien.email: 'skien.vgs@t-fk.no'
    footer.skien.phone: 'Avd. Prestejordet: 35 91 80 00'
    footer.skien.phone2: 'Avd. Brekkeby: 35 91 80 50'
    footer.skien.post: 'Postboks 2844, 3702 Skien'
    footer.skien.adress: 'Avd. Prestejordet: Einar Østvedts gate 12, 3724 Skien'
    footer.skien.adress2: 'Avd. Brekkeby: Rektor Ørns gate 2, 3717 Skien'

    footer.skien.contact: 'Webmaster'
    footer.skien.link: 'http://apps.t-fk.no/ansatte/#/ansatt/11165'
    footer.skien.fblink: 'https://www.facebook.com/skienvgs/'
    footer.skien.fb: 'Facebook'
    footer.skien.youtube: 'https://www.youtube.com/channel/UCSaA2KXfm__BkVYb49P2ACg'

    head.skogmo.logo: 'skogmo_toplogo.png'
    head.skogmo.title: 'Skogmo videregående skole'
    head.skogmo.meta_author: 'Skogmo videregående skole'
    head.skogmo.meta_description: 'Skogmo videregående skole er en fin skole'
    head.skogmo.meta_keywords: 'skogmo'

    footer.skogmo.email: 'skogmo.vgs@t-fk.no'
    footer.skogmo.phone: '35 91 92 00'
    footer.skogmo.post: 'Kjørbekkdalen 11, 3735 Skien'
    footer.skogmo.adress: 'Kjørbekkdalen 11, Skien'
    footer.skogmo.contact: 'Webmaster'
    footer.skogmo.link: 'http://apps.t-fk.no/ansatte/#/ansatt/8491'
    footer.skogmo.fblink: 'https://www.facebook.com/Skogmovgs/'
    footer.skogmo.fb: 'Facebook'

    head.fagskolen.logo: 'fagskolen_toplogo.png'
    head.fagskolen.title: 'Fagskolen telemark'
    head.fagskolen.meta_author: 'Fagskolen telemark'
    head.fagskolen.meta_description: 'Fagskolen telemark er en fin skole'
    head.fagskolen.meta_keywords: 'fagskolen telemark'

    footer.fagskolen.email: 'post@fagskolentelemark.no'
    footer.fagskolen.phone: '35 91 77 50'
    footer.fagskolen.post: 'Postboks 2844, 3702 Skien'
    footer.fagskolen.adress: 'Kjølnes Ring 26, 3918 Porsgrunn'
    footer.fagskolen.contact: 'Webmaster'
    footer.fagskolen.link: 'http://apps.t-fk.no/ansatte/#/ansatt/11922'
    footer.fagskolen.fblink: 'https://www.facebook.com/FagskolenTelemark?ref=hl'
    footer.fagskolen.fb: 'Facebook'
    footer.fagskolen.twitter: 'https://twitter.com/fagskolen'
    footer.fagskolen.youtube: 'https://www.youtube.com/channel/UC9eKxv7J1hc2iKCMGSg6kQg'
    footer.fagskolen.flickr: 'https://www.flickr.com/photos/107959030@N03/albums/with/72157654237948960'
    footer.fagskolen.linkedin: 'https://www.linkedin.com/company/fagskolen-telemark'